.PHONY: run
run:
	@ dune exec list_like_benchmark && dune exec benchmark

.PHONY: list_like_benchmark benchmark
list_like_benchmark:
	@ dune exec list_like_benchmark
benchmark:
	@ dune exec benchmark
